name: Check Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint
